services:
  anidl:
    build: .
    container_name: anidl
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - type: bind
        source: ./videos
        target: /usr/local/bin/multi-downloader-nx-linux-x64-cli/videos

      - type: bind
        source: ./widevine
        target: /usr/local/bin/multi-downloader-nx-linux-x64-cli/widevine

      - type: bind
        source: ./playready
        target: /usr/local/bin/multi-downloader-nx-linux-x64-cli/playready

      - type: bind
        source: ./fonts
        target: /usr/local/bin/multi-downloader-nx-linux-x64-cli/fonts

      - type: bind
        source: ./config
        target: /usr/local/bin/multi-downloader-nx-linux-x64-cli/config
